### Update a patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Mehmet Ali bey",
  "email": "testing@test.com",
  "address": "123 main street",
  "dateOfBirth": "1996-12-22"
}


###